services:
  restapi-currency:
    image: belyaevedu/restapi-currency:${IMAGE_TAG:-latest}

    restart: unless-stopped

    build:
      context: .
      args:
        - PORT=${PORT-8000}
        - PROMETHEUS_PORT=${PROMETHEUS_PORT-9100}

    env_file:
      - .env

    ports:
      - "${PORT-8000}:${PORT-8000}"
      - "${PROMETHEUS_PORT-9100}:${PROMETHEUS_PORT-9100}"

    networks:
      - restapi-currency-network

    user: "1000:1000"

    read_only: true
    tmpfs:
      - /app/requester/cache:uid=1000,gid=1000
      - /tmp:uid=1000,gid=1000

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE


networks:
  restapi-currency-network:
    driver: bridge
