- name: Assert that crio_install_version variable is >={{ crio_install_minimal_version }}
  ansible.builtin.assert:
    that:
      - "crio_install_version is version(crio_install_minimal_version, '>=')"
    fail_msg: "CRI-O version specified to be {{ crio_install_version }}. Should be at least {{ crio_install_minimal_version }}"

- name: Add the cri-o apt repository
  ansible.builtin.deb822_repository:
    name: cri-o
    types: [deb]
    uris: "https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_install_version }}/deb/"
    suites: ["/"]
    signed_by: "https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_install_version }}/deb/Release.key"
    state: present
    enabled: true

- name: Install the cri-o package
  ansible.builtin.apt:
    name:
      - cri-o
    state: present
    update_cache: true

- name: Start cri-o
  ansible.builtin.systemd_service:
    name: cri-o
    state: started
