apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: currency-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/belyaevEDU/devops-app-helm.git
    path: currency
    targetRevision: HEAD
    helm:
      valueFiles:
        - 00-values.yaml
        - 01-values.production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: currency-app-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
