apiVersion: apps/v1
kind: Deployment
metadata:
  name: frpc
  namespace: frpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frpc
  template:
    metadata:
      labels:
        app: frpc
        currency-observability: "true"
    spec:
      containers:
        - name: frpc
          image: snowdreamtech/frpc
          volumeMounts:
            - name: frpc-config
              mountPath: /etc/frp/frpc.toml
              subPath: frpc.toml
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/secret-volume"
      volumes:
        - name: frpc-config
          configMap:
            name: frpc-config
        - name: secret-volume
          secret:
            secretName: frpc-token-dotfile
