apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: currency-updater-production
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "currency-app-prod"
      images:
        - alias: "restapi-currency"
          imageName: "belyaevedu/restapi-currency:v1.x"
          commonUpdateSettings:
            pullSecret: "pullsecret:argocd/dockerhub-creds"
            updateStrategy: "semver"
          manifestTargets:
            helm:
              name: "image.repository"
              tag: "image.tag"
  writeBackConfig:
    method: "git"
    gitConfig:
      repository: "https://github.com/belyaevEDU/devops-app-helm.git"
      branch: "main"
      writeBackTarget: "helmvalues:00-values.yaml"